spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost/testdb
    username: root
    password: 123456
kafka:
  topic: 'my_topic'
  bootstrap:
    servers: 'localhost:9092'
